# AUTO-GENERATED from test plan: docs/testing-plans/raft-cr-project-stability.md
# Scenario: S05 durability_survives_crash_mid_persist_state
# Falsifies: C7, C8, C18, C20, C21 (persistent state durability; no torn meta;
#            bootstrap exclusivity; recover_state correctness; raft_meta.tmp cleanup)
# Plan sha at generation: c58aefdaa18581a3382c6594af7e995e6bc2af4b
#
# REVIEW BEFORE TREATING AS A PERMANENT REGRESSION:
# this file was generated by executing-distributed-system-tests in author mode.
#
# Workload: bootstrap a single-voter node and loop propose() until SIGKILLed.
# Helper runs in a subprocess (avoids preview_mt fork pitfalls); the spec spawns
# it, kills it at a random offset, then reopens the data dir and asserts the
# durability invariants.

require "../../spec_helper"

ITERATIONS = (ENV["S05_ITERS"]? || "30").to_i

HELPER_SRC = File.expand_path("./durability_helper.cr", __DIR__)

describe "S05: durability_survives_crash_mid_persist_state (plan §7 S05)" do
  helper_bin = ""

  before_all do
    helper_bin = File.tempname("s05_helper")
    stdout_io = IO::Memory.new
    stderr_io = IO::Memory.new
    status = Process.run("crystal", [
      "build", "-Dpreview_mt", "-Dexecution_context",
      "--no-color", "-o", helper_bin, HELPER_SRC,
    ], output: stdout_io, error: stderr_io)
    unless status.success? && File.exists?(helper_bin)
      raise "S05: failed to build durability_helper: #{stderr_io}"
    end
  end

  it "recovers consistently after SIGKILL at random points" do
    rng = Random.new(20260523_u64) # deterministic seed
    inconsistencies = [] of String

    ITERATIONS.times do |i|
      dir = File.tempname("s05_iter_#{i}")
      Dir.mkdir_p(dir)
      begin
        # Spawn child; let it run for a random window of 10-200 ms.
        proc = Process.new(
          helper_bin, [dir],
          input: Process::Redirect::Close,
          output: Process::Redirect::Close,
          error: Process::Redirect::Close,
        )
        sleep_ms = rng.rand(10..200)
        sleep sleep_ms.milliseconds
        proc.signal(Signal::KILL) rescue nil
        proc.wait

        # Open fresh; recover_state runs in initialize.
        cfg = Raft::Config.new
        cfg.data_dir = dir
        cfg.election_timeout_min_ticks = 5_u32
        cfg.election_timeout_max_ticks = 5_u32
        cfg.heartbeat_ticks = 100_u32

        sm = TestStateMachine.new
        node = Raft::Node(TestData).new(
          id: 1_u64, peers: [] of Raft::NodeID, config: cfg, state_machine: sm,
        )

        # Invariant 1: no leftover .tmp file (C8, C21).
        tmp = File.join(dir, "raft_meta.tmp")
        inconsistencies << "iter=#{i} leftover #{tmp}" if File.exists?(tmp)

        # Invariant 2: commit_index <= log.last_index (M7 — surfaced).
        unless node.commit_index <= node.log.last_index
          inconsistencies << "iter=#{i} commit_index=#{node.commit_index} > last_index=#{node.log.last_index}"
        end

        # Invariant 3: term >= 1 (bootstrap set term=1 in the child) (C18, C20).
        unless node.current_term >= 1_u64
          inconsistencies << "iter=#{i} term=#{node.current_term} after bootstrap+kill"
        end

        # Invariant 4: peers list non-empty and includes self (C20, C7).
        unless node.peers.any? { |p| p.id == 1_u64 }
          inconsistencies << "iter=#{i} self missing from recovered peers: #{node.peers.map(&.id)}"
        end

        # Invariant 5: voted_for is self (bootstrap path) OR nil after crash
        # mid-write of raft_meta — but the typed durability contract says
        # tmp+rename means either the previous valid state OR the new state,
        # never half. We can't predict which, but we can assert the value is
        # in {nil, 1_u64}.
        vf = node.voted_for
        unless vf.nil? || vf == 1_u64
          inconsistencies << "iter=#{i} unexpected voted_for=#{vf.inspect}"
        end

        node.close
      ensure
        FileUtils.rm_rf(dir)
      end
    end

    if !inconsistencies.empty?
      fail "S05 found #{inconsistencies.size} inconsistencies:\n" + inconsistencies.first(10).join("\n")
    end
  end

  after_all do
    File.delete(helper_bin) if !helper_bin.empty? && File.exists?(helper_bin)
  end
end
