# AUTO-GENERATED from test plan: docs/testing-plans/raft-cr-project-stability.md
# Scenario: S16 replication_perf_slo_gate
# Falsifies: implicit perf SLO (no documented absolute numbers; this run
#            establishes a baseline that future runs can gate against).
# Plan sha at generation: c58aefdaa18581a3382c6594af7e995e6bc2af4b
#
# REVIEW BEFORE TREATING AS A PERMANENT REGRESSION:
# this file was generated by executing-distributed-system-tests in author mode.
#
# In-process: single-voter cluster, propose N entries, measure per-entry latency.
# Outputs JSON to test-sessions/.../metrics/s16_perf.json. No regression gate
# yet (first run establishes the baseline).

require "../../spec_helper"
require "json"

class PerfSM < Raft::StateMachine(TestData)
  getter applied = 0

  def apply(entry : TestData)
    @applied += 1
  end

  def snapshot(io : IO); end

  def restore(io : IO); end
end

describe "S16: replication_perf_slo_gate (plan §7 S16)" do
  it "establishes a single-voter propose latency baseline" do
    dir = File.tempname("s16_perf")
    Dir.mkdir_p(dir)
    cfg = Raft::Config.new
    cfg.data_dir = dir
    cfg.election_timeout_min_ticks = 100_u32
    cfg.election_timeout_max_ticks = 100_u32
    cfg.heartbeat_ticks = 200_u32
    cfg.snapshot_interval_entries = 1_000_000_u64

    sm = PerfSM.new
    node = Raft::Node(TestData).new(
      id: 1_u64, peers: [] of Raft::NodeID, config: cfg, state_machine: sm,
    )
    node.bootstrap.should be_true

    # Warm-up
    50.times { node.propose(TestData.new("warm")) }

    # Measured run — keep small to keep the suite quick.
    n = (ENV["S16_N"]? || "500").to_i
    latencies_ns = Array(Int64).new(n)
    n.times do
      t0 = Time.instant
      node.propose(TestData.new("payload-of-modest-size-32B-here!!"))
      latencies_ns << (Time.instant - t0).total_nanoseconds.to_i64
    end

    latencies_ns.sort!
    p50_us = latencies_ns[(n * 0.50).to_i] / 1000.0
    p95_us = latencies_ns[(n * 0.95).to_i] / 1000.0
    p99_us = latencies_ns[(n * 0.99).to_i] / 1000.0
    pmax_us = latencies_ns.last / 1000.0
    mean_us = (latencies_ns.sum / n) / 1000.0

    metrics_dir = File.expand_path(
      "../../../test-sessions/raft-cr-project-stability/20260523T134204Z/metrics",
      __DIR__,
    )
    Dir.mkdir_p(metrics_dir)
    File.write(
      File.join(metrics_dir, "s16_perf.json"),
      {
        scenario:      "S16 replication_perf_slo_gate",
        workload:      "single-voter propose; warm=50; n=#{n}; payload=~32B",
        latencies_us:  {p50: p50_us, p95: p95_us, p99: p99_us, max: pmax_us, mean: mean_us},
        node_state:    {commit_index: node.commit_index.to_i64, log_last_index: node.log.last_index.to_i64},
        baseline_only: true,
      }.to_json,
    )

    # No regression gate — this run *is* the baseline. Assert sanity only.
    p50_us.should be > 0.0
    sm.applied.should be >= n

    node.close
    FileUtils.rm_rf(dir)
  end
end
