# AUTO-GENERATED from test plan: docs/testing-plans/raft-cr-project-stability.md
# Scenario: S10 apply_once_in_order_across_snapshot_boundary
# Falsifies: C23 (apply-once, in-order, across snapshot boundary)
# Plan sha at generation: c58aefdaa18581a3382c6594af7e995e6bc2af4b
#
# REVIEW BEFORE TREATING AS A PERMANENT REGRESSION:
# this file was generated by executing-distributed-system-tests in author mode.
# Verify the workload, faults, and oracle below match the plan's intent.

require "../spec_helper"

# Recording state machine that captures (index_observed, payload) in apply-order.
# We can't see the log index from inside apply(), so we tag payloads with a
# sequence number from the caller and assert apply-order matches issue-order.
class SeqRecordingSM < Raft::StateMachine(TestData)
  getter applied : Array(String) = [] of String
  property snapshot_called : Int32 = 0

  def apply(entry : TestData)
    @applied << entry.value
  end

  def snapshot(io : IO)
    @snapshot_called += 1
    io.write_bytes(@applied.size.to_u32, IO::ByteFormat::LittleEndian)
    @applied.each do |v|
      io.write_bytes(v.bytesize.to_u32, IO::ByteFormat::LittleEndian)
      io.write(v.to_slice)
    end
  end

  def restore(io : IO)
    @applied.clear
    n = io.read_bytes(UInt32, IO::ByteFormat::LittleEndian)
    n.times do
      sz = io.read_bytes(UInt32, IO::ByteFormat::LittleEndian)
      buf = Bytes.new(sz)
      io.read_fully(buf) if sz > 0
      @applied << String.new(buf)
    end
  end
end

describe "S10: apply_once_in_order_across_snapshot_boundary (plan §7 S10)" do
  it "applies entries in strictly increasing order with no duplicates across a snapshot+restart cycle" do
    dir = File.tempname("s10_apply_invariants")
    Dir.mkdir_p(dir)
    begin
      config = Raft::Config.new
      config.data_dir = dir
      config.election_timeout_min_ticks = 5_u32
      config.election_timeout_max_ticks = 5_u32
      config.heartbeat_ticks = 100_u32
      config.snapshot_interval_entries = 25_u64 # force snapshot mid-workload

      sm = SeqRecordingSM.new
      node = Raft::Node(TestData).new(
        id: 1_u64, peers: [] of Raft::NodeID, config: config, state_machine: sm,
      )
      node.bootstrap.should be_true

      # Issue ordered proposals. Single-voter bootstrap commits each immediately.
      n_props = 80
      n_props.times do |i|
        node.propose(TestData.new("seq-#{i.to_s.rjust(4, '0')}")).should be_true
      end

      # Oracle pre-restart: apply order matches issue order; no duplicates; no gaps.
      sm.applied.size.should eq n_props
      sm.applied.each_with_index do |v, i|
        v.should eq "seq-#{i.to_s.rjust(4, '0')}"
      end
      # Snapshot must have fired at least once (n_props > snapshot_interval_entries).
      sm.snapshot_called.should be > 0

      # Restart — recovery should load snapshot then replay any entries past it.
      node.close
      sm2 = SeqRecordingSM.new
      node2 = Raft::Node(TestData).new(
        id: 1_u64, peers: [] of Raft::NodeID, config: config, state_machine: sm2,
      )

      # Oracle post-restart: entire applied sequence is present in order, exactly once.
      sm2.applied.size.should eq n_props
      sm2.applied.each_with_index do |v, i|
        v.should eq "seq-#{i.to_s.rjust(4, '0')}"
      end

      # Apply-once invariant: no duplicate values (Set has the same cardinality).
      sm2.applied.to_set.size.should eq n_props

      # Recovered last_applied / commit_index sanity.
      node2.commit_index.should eq node2.log.last_index
      node2.commit_index.should be >= n_props.to_u64

      node2.close
    ensure
      FileUtils.rm_rf(dir)
    end
  end

  it "applied sequence survives an immediate restart (no new proposals)" do
    # Exercises pure recovery — same dir, fresh Node, verify the SM was
    # restored from snapshot/log and the applied sequence is intact.
    dir = File.tempname("s10_restart_only")
    Dir.mkdir_p(dir)
    begin
      cfg = Raft::Config.new
      cfg.data_dir = dir
      cfg.election_timeout_min_ticks = 5_u32
      cfg.election_timeout_max_ticks = 5_u32
      cfg.heartbeat_ticks = 100_u32
      cfg.snapshot_interval_entries = 15_u64

      sm1 = SeqRecordingSM.new
      n1 = Raft::Node(TestData).new(id: 1_u64, peers: [] of Raft::NodeID, config: cfg, state_machine: sm1)
      n1.bootstrap.should be_true
      40.times { |i| n1.propose(TestData.new("v-#{i.to_s.rjust(4, '0')}")).should be_true }
      pre_apply_count = sm1.applied.size
      n1.close

      sm2 = SeqRecordingSM.new
      n2 = Raft::Node(TestData).new(id: 1_u64, peers: [] of Raft::NodeID, config: cfg, state_machine: sm2)
      sm2.applied.size.should eq pre_apply_count
      sm2.applied.each_with_index do |v, i|
        v.should eq "v-#{i.to_s.rjust(4, '0')}"
      end
      sm2.applied.to_set.size.should eq pre_apply_count
      n2.close
    ensure
      FileUtils.rm_rf(dir)
    end
  end

  it "single-voter cluster re-elects itself after restart (F1 regression test)" do
    # Before the fix in src/raft/node.cr, start_pre_vote/become_candidate did
    # not short-circuit on self-vote-only quorum, so a post-restart single-
    # voter cluster (role recovered as Follower, peers={self}) could never
    # become Leader again — propose() returned false forever. The fix adds
    # a quorum check after the self-vote in both functions.
    dir = File.tempname("s10_single_voter_restart")
    Dir.mkdir_p(dir)
    begin
      cfg = Raft::Config.new
      cfg.data_dir = dir
      cfg.election_timeout_min_ticks = 5_u32
      cfg.election_timeout_max_ticks = 5_u32
      cfg.heartbeat_ticks = 100_u32

      total = 0
      3.times do |cycle|
        sm = SeqRecordingSM.new
        node = Raft::Node(TestData).new(
          id: 1_u64, peers: [] of Raft::NodeID, config: cfg, state_machine: sm,
        )
        if cycle == 0
          node.bootstrap.should be_true
        else
          # On restart, the node recovers as Follower with peers={self}.
          # Drive ticks until the election timer fires — the F1 fix lets
          # start_pre_vote → become_candidate → become_leader cascade
          # immediately when self alone satisfies quorum.
          node.role.should eq Raft::Role::Follower
          node.peers.map(&.id).should eq [1_u64]
          ticks = 0
          while node.role != Raft::Role::Leader && ticks < 50
            node.tick
            ticks += 1
          end
          node.role.should eq Raft::Role::Leader
        end
        20.times do
          node.propose(TestData.new("c#{cycle}-#{total.to_s.rjust(4, '0')}")).should be_true
          total += 1
        end
        # Fresh SM saw `total` apply()s this cycle: recover_state replayed
        # (cycle * 20) prior committed entries, then we just appended 20 more.
        # Plus a Noop per become_leader transition (bootstrap appends one;
        # each restart's election appends another), which the SM skips.
        sm.applied.size.should eq total
        node.close
      end
      total.should eq 60
    ensure
      FileUtils.rm_rf(dir)
    end
  end
end
