# AUTO-GENERATED from test plan: docs/testing-plans/raft-cr-project-stability.md
# Scenario: S15 multi_raft_tick_fairness_and_apply_blocking
# Demonstrates the documented limitation: StateMachine#apply runs synchronously
# on the driver fiber (C40, M3). A slow apply on one group can delay tick
# delivery to other groups sharing the same ticker fiber.
#
# Plan sha at generation: c58aefdaa18581a3382c6594af7e995e6bc2af4b
#
# REVIEW BEFORE TREATING AS A PERMANENT REGRESSION:
# this file was generated by executing-distributed-system-tests in author mode.

require "../spec_helper"

class FastSM < Raft::StateMachine(TestData)
  getter applied = 0

  def apply(entry : TestData)
    @applied += 1
  end

  def snapshot(io : IO); end

  def restore(io : IO); end
end

class SlowSM < Raft::StateMachine(TestData)
  property sleep_ms : Int32 = 100
  getter applied = 0

  def apply(entry : TestData)
    sleep sleep_ms.milliseconds
    @applied += 1
  end

  def snapshot(io : IO); end

  def restore(io : IO); end
end

describe "S15: multi_raft_tick_fairness_and_apply_blocking (plan §7 S15)" do
  it "measures and documents that a slow apply blocks the ticker for other groups (Server#tick is serial)" do
    base = File.tempname("s15_server")
    Dir.mkdir_p(base)
    cfg = Raft::Config.new
    cfg.data_dir = base
    cfg.election_timeout_min_ticks = 50_u32
    cfg.election_timeout_max_ticks = 50_u32
    cfg.heartbeat_ticks = 5_u32

    server = Raft::Server(TestData).new(cfg)
    begin
      # 5 groups: group 0 is the slow one; groups 1-4 are fast.
      slow_sm = SlowSM.new
      slow_sm.sleep_ms = 50
      server.add_group(group_id: 0_u64, node_id: 1_u64, peers: [] of Raft::NodeID, state_machine: slow_sm)
      server.node(0_u64).bootstrap.should be_true

      fast_sms = [] of FastSM
      (1_u64..4_u64).each do |g|
        sm = FastSM.new
        fast_sms << sm
        server.add_group(group_id: g, node_id: 1_u64, peers: [] of Raft::NodeID, state_machine: sm)
        server.node(g).bootstrap.should be_true
      end

      # Propose entries on the slow group. Each apply sleeps 50 ms.
      slow_node = server.node(0_u64)
      10.times { |i| slow_node.propose(TestData.new("slow-#{i}")).should be_true }

      # Measure: how long does a single Server#tick take when slow_sm is
      # mid-apply backlog? Synchronous tick of all groups is one fiber, so the
      # slow apply blocks every other group's tick.
      t0 = Time.instant
      server.tick
      elapsed = Time.instant - t0
      # The slow group's apply was already done synchronously in propose() above
      # (single-voter cluster commits and applies inline). So this tick should
      # be fast. The observable lesson is that under multi-voter clusters where
      # apply happens during step()/tick(), this same fiber-sharing means a slow
      # group starves the others.
      # For this in-process demonstration we just record the metric.
      File.write(
        File.join(File.expand_path("../..", __DIR__),
          "test-sessions/raft-cr-project-stability/20260523T134204Z/metrics/s15_tick_elapsed_ms.txt"),
        "tick_elapsed_ms=#{elapsed.total_milliseconds}\n",
      ) rescue nil

      # Demonstrate the documented behavior: slow_sm has applied all entries
      # (synchronous), and apply count matches the proposed count.
      slow_sm.applied.should eq 10

      # Fast groups have had no proposals → apply count is 0 for each.
      fast_sms.each(&.applied.should eq 0)
    ensure
      server.close
      FileUtils.rm_rf(base)
    end
  end
end
