# AUTO-GENERATED from test plan: docs/testing-plans/raft-cr-project-stability.md
# Scenario: S12 serialization_and_message_parser_fuzz
# Falsifies: C31 (max payload check); surfaces M6 (per-entry T#from_io exception isolation)
# Plan sha at generation: c58aefdaa18581a3382c6594af7e995e6bc2af4b
#
# REVIEW BEFORE TREATING AS A PERMANENT REGRESSION:
# this file was generated by executing-distributed-system-tests in author mode.
# Verify the workload, faults, and oracle below match the plan's intent.

require "../spec_helper"

# Bounded random-input fuzz of the wire-format parsers. The invariant under test:
# parsers never panic on arbitrary input — they either succeed with a valid value
# or raise a typed I/O / overflow / argument error.

ALLOWED_ERROR_CLASSES = [
  IO::EOFError,
  IO::Error,
  ArgumentError,
  OverflowError,
  IndexError,
] of Class

def assert_only_typed_errors(input_label : String, &block)
  begin
    block.call
  rescue ex : IO::EOFError | IO::Error | ArgumentError | OverflowError | IndexError
    # Typed parser error — acceptable.
  rescue ex
    raise "FUZZ FAIL (#{input_label}): unexpected exception #{ex.class}: #{ex.message}"
  end
end

describe "S12: serialization_and_message_parser_fuzz (plan §7 S12)" do
  it "Message.from_io never panics on random bytes within max_payload" do
    max_payload = 1_u32 * 1024_u32 * 1024_u32 # 1 MB
    rng = Random.new(42_u64)                  # deterministic seed for reproducibility
    iters = 2_000

    iters.times do |i|
      # Pick a random length in [0, 256] — most useful coverage is at short
      # boundary lengths; a 1 MB random buffer would mostly produce header-size
      # rejection without exploring parser branches.
      len = rng.rand(0..256)
      buf = Bytes.new(len)
      rng.random_bytes(buf)
      assert_only_typed_errors("Message.from_io iter=#{i} len=#{len}") do
        Raft::Message.from_io(IO::Memory.new(buf), max_payload)
      end
    end
  end

  it "Message.from_io rejects oversized entries_data payload (C31 — exact bound)" do
    # Constructed payload that lies about its entries_data size: claims max+1
    # but the buffer is short. from_io should raise before allocating.
    max_payload = 1024_u32
    io = IO::Memory.new
    io.write_bytes(1_u8, IO::ByteFormat::LittleEndian)                # protocol_version
    io.write_bytes(0_u64, IO::ByteFormat::LittleEndian)               # group_id
    io.write_bytes(0_u8, IO::ByteFormat::LittleEndian)                # type AppendEntries
    io.write_bytes(0_u64, IO::ByteFormat::LittleEndian)               # from
    io.write_bytes(0_u64, IO::ByteFormat::LittleEndian)               # term
    io.write_bytes(0_u64, IO::ByteFormat::LittleEndian)               # prev_log_index
    io.write_bytes(0_u64, IO::ByteFormat::LittleEndian)               # prev_log_term
    io.write_bytes(0_u64, IO::ByteFormat::LittleEndian)               # commit_index
    io.write_bytes(0_u64, IO::ByteFormat::LittleEndian)               # last_log_index
    io.write_bytes(0_u64, IO::ByteFormat::LittleEndian)               # last_log_term
    io.write_bytes(0_u8, IO::ByteFormat::LittleEndian)                # success
    io.write_bytes(0_u64, IO::ByteFormat::LittleEndian)               # reject_hint
    io.write_bytes(0_u32, IO::ByteFormat::LittleEndian)               # entries_count
    io.write_bytes(max_payload + 1_u32, IO::ByteFormat::LittleEndian) # data_size > max_payload
    io.rewind

    ex = expect_raises(IO::Error) do
      Raft::Message.from_io(io, max_payload)
    end
    ex.message.not_nil!.should contain "max_message_payload_bytes"
  end

  it "LogEntry.from_io never panics on random bytes" do
    rng = Random.new(43_u64)
    iters = 2_000
    iters.times do |i|
      len = rng.rand(0..128)
      buf = Bytes.new(len)
      rng.random_bytes(buf)
      assert_only_typed_errors("LogEntry.from_io iter=#{i} len=#{len}") do
        Raft::LogEntry(TestData).from_io(IO::Memory.new(buf))
      end
    end
  end

  it "Peer.from_io never panics on random bytes" do
    rng = Random.new(44_u64)
    iters = 1_000
    iters.times do |i|
      len = rng.rand(0..64)
      buf = Bytes.new(len)
      rng.random_bytes(buf)
      assert_only_typed_errors("Peer.from_io iter=#{i} len=#{len}") do
        Raft::Peer.from_io(IO::Memory.new(buf))
      end
    end
  end

  it "Message round-trips for a corpus of well-formed inputs" do
    msgs = [
      Raft::Message.new(type: Raft::MessageType::AppendEntries, from: 1_u64, term: 0_u64),
      Raft::Message.new(type: Raft::MessageType::PreVote, from: 2_u64, term: 1_u64, last_log_index: 5_u64, last_log_term: 1_u64),
      Raft::Message.new(type: Raft::MessageType::RequestVoteResponse, from: 3_u64, term: 1_u64, success: true),
      Raft::Message.new(type: Raft::MessageType::AppendEntries, from: 1_u64, term: 2_u64,
        entries_data: Bytes.new(8), entries_count: 1_u32),
    ]
    msgs.each_with_index do |m, i|
      buf = IO::Memory.new
      m.to_io(buf)
      buf.rewind
      decoded = Raft::Message.from_io(buf, 1_u32 << 20)
      decoded.type.should eq m.type
      decoded.from.should eq m.from
      decoded.term.should eq m.term
      decoded.entries_count.should eq m.entries_count
    end
  end
end
