# AUTO-GENERATED from test plan: docs/testing-plans/raft-cr-project-stability.md
# Scenario: S02 at_most_one_leader_per_term_under_split_vote
# Falsifies: C2, C3, C15 (election restriction; at-most-one-leader-per-term; pre-vote anti-inflation)
# Plan sha at generation: c58aefdaa18581a3382c6594af7e995e6bc2af4b
#
# REVIEW BEFORE TREATING AS A PERMANENT REGRESSION:
# this file was generated by executing-distributed-system-tests in author mode.
#
# This is a deterministic-simulation arm of the plan's intended T4 technique. The
# library's Node(T) is already a step/tick state machine with no internal I/O, so
# scenarios can be replayed bit-exact from a seed.
#
# Each seed drives a 5-node cluster with adversarial random scheduling of message
# delivery + tick firing + (rare) message drops. The structural invariant
# `forall term, |{n : n.role = Leader && n.current_term = term}| ≤ 1` is asserted
# after every step.

require "../../spec_helper"

# Plan calls for 100k seeds. For a CI-runnable budget we use 200 seeds × 200
# steps each (40k step-invariant checks); the spec is structured so the count
# can be increased via the S02_SEEDS env var without code changes.
SEED_COUNT     = (ENV["S02_SEEDS"]? || "200").to_i
STEPS_PER_SEED = (ENV["S02_STEPS"]? || "200").to_i

def build_5_node_cluster(seed : UInt64, base_dir : String) : Hash(Raft::NodeID, Raft::Node(TestData))
  cfg_template = Raft::Config.new
  cfg_template.election_timeout_min_ticks = 5_u32
  cfg_template.election_timeout_max_ticks = 12_u32
  cfg_template.heartbeat_ticks = 2_u32

  nodes = {} of Raft::NodeID => Raft::Node(TestData)
  (1_u64..5_u64).each do |id|
    cfg = Raft::Config.new
    cfg.election_timeout_min_ticks = cfg_template.election_timeout_min_ticks
    cfg.election_timeout_max_ticks = cfg_template.election_timeout_max_ticks
    cfg.heartbeat_ticks = cfg_template.heartbeat_ticks
    cfg.data_dir = File.join(base_dir, "n#{id}")
    Dir.mkdir_p(cfg.data_dir)
    peers = (1_u64..5_u64).reject { |x| x == id }.to_a
    sm = TestStateMachine.new
    nodes[id] = Raft::Node(TestData).new(
      id: id, peers: peers, config: cfg, state_machine: sm,
    )
  end
  nodes
end

def leaders_per_term(nodes : Hash(Raft::NodeID, Raft::Node(TestData))) : Hash(UInt64, Array(Raft::NodeID))
  ht = Hash(UInt64, Array(Raft::NodeID)).new { |h, k| h[k] = [] of Raft::NodeID }
  nodes.each do |id, node|
    if node.role == Raft::Role::Leader
      ht[node.current_term] << id
    end
  end
  ht
end

describe "S02: at_most_one_leader_per_term_under_split_vote (plan §7 S02)" do
  it "never elects two leaders in one term across #{SEED_COUNT} random schedules" do
    failures = [] of {UInt64, UInt64, Array(Raft::NodeID)}
    seeds_that_saw_a_leader = 0
    max_term_observed = 0_u64
    total_invariant_checks = 0
    SEED_COUNT.times do |seed_int|
      seed = seed_int.to_u64
      rng = Random.new(seed)
      base_dir = File.tempname("s02_seed_#{seed}")
      Dir.mkdir_p(base_dir)
      saw_leader = false
      begin
        nodes = build_5_node_cluster(seed, base_dir)
        in_flight = [] of {Raft::NodeID, Raft::Message}
        STEPS_PER_SEED.times do
          # Action mix:
          #   60% deliver one pending message (if any)
          #   25% tick a random node
          #   10% drain a node's outbox into in_flight
          #   5% drop the oldest in-flight message (network loss)
          action = rng.rand(100)
          if action < 60 && !in_flight.empty?
            target_id, msg = in_flight.shift
            nodes[target_id].step(msg) if nodes.has_key?(target_id)
          elsif action < 85
            nid = rng.rand(1..5).to_u64
            nodes[nid].tick
          elsif action < 95
            nid = rng.rand(1..5).to_u64
            nodes[nid].take_messages.each { |t, m| in_flight << {t, m} }
          else
            in_flight.shift unless in_flight.empty?
          end
          # Drain everyone occasionally to keep the queue tractable
          if rng.rand(100) < 20
            nodes.each_value do |n|
              n.take_messages.each { |t, m| in_flight << {t, m} }
            end
          end

          # Invariant: at-most-one leader per term.
          lpt = leaders_per_term(nodes)
          total_invariant_checks += 1
          lpt.each do |term, leaders|
            saw_leader = true if leaders.size >= 1
            max_term_observed = term if term > max_term_observed
            if leaders.size > 1
              failures << {seed, term, leaders}
              break
            end
          end
          break unless failures.empty? || failures.last[0] != seed
        end
        seeds_that_saw_a_leader += 1 if saw_leader
        nodes.each_value(&.close)
      ensure
        FileUtils.rm_rf(base_dir)
      end
      break unless failures.empty?
    end

    if !failures.empty?
      seed, term, leaders = failures.first
      fail "FAIL: seed=#{seed} term=#{term} elected #{leaders.size} leaders: #{leaders}"
    end

    # Sanity / weak-oracle guard: if the workload never produced any leader at
    # all, the invariant is trivially satisfied and we'd be reporting a
    # green-but-broken result. Require at least 50% of seeds to elect a leader
    # at least once during their run; bail with a diagnostic message if not.
    puts "  [S02] seeds_that_saw_a_leader=#{seeds_that_saw_a_leader}/#{SEED_COUNT} " \
         "max_term_observed=#{max_term_observed} " \
         "invariant_checks=#{total_invariant_checks}"
    seeds_that_saw_a_leader.should be > (SEED_COUNT // 2)
  end
end
